spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bets
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          custom-provider:
            client-id: teste123
            client-secret: secret123
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          custom-provider:
            authorization-uri: http://localhost:8089/oauth/authorize
            token-uri: http://localhost:8089/oauth/token
            user-info-uri: http://localhost:8089/oauth/api/user
            user-name-attribute: id

server:
  port: 8088
  servlet:
    context-path: /api/


jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

