spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bets
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: bets
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8088